# This provides us with GCC binary support so we can run bash
language: generic

# Try to supply the packages from Travis so that when we run build.sh we won't
# be required to download them again.
include:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - debootstrap
          - genisoimage
          - p7zip-full
          - squashfs-tools
          - ubuntu-dev-tools
          - dpkg-dev
          - debhelper
          - fakeroot
          - devscripts

sudo: required

script:
  - chmod +x ./build.sh
  - ./build.sh

before_deploy:
  - export image_name="`echo *.iso`"
  - cat *.iso > "/home/travis/${image_name}"

after_deploy:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/releases_maintainer.sh; fi'

notifications:
  slack: fossasia:3pMkQrSogvEMfnu9aJDW2ZYC

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "mgmk0wO6V1XH8N8ACWZ6nxNy6CbUJcB1p+6WEqHK4g70thEjEM4h0TlTA3hrCvAWsaHtrkTh4jff1lZhQ7APxBYdhOx/S4+GfD9GJGcDgU6PWvUPxfdjBhU+7pymzFOOWt1vZmg5KpZRnCHSPeRjQD1Ik9c5vhhjz4BlDEdCuE5whgOlnMLu1iX0U9zbP4ywe8cggkV56+/6bavgXNJrEfcaKOtQamSjcrBuu9JcTjmkmzp88n9/wwp8WyfojXrGf+AgY+U0UFjwhx9mAaf1eq0ScNag3TE0zq13NEYYh17jmCLQ+XYclRVSQ2cAAv9l5Hk/4NzJINRvCzpkAL4GI01Pw8uA6xVsMy75bwjLaaRjL746jPdUpx9yM9SvE875scj5980RBFUbegqUVJnmutsx5ola/6tUbno4UOap+B73oyLNRF9Mko+nyJVt348ajqx6uavm6pC6bQZQA6x2tCaPYnw8JbCzV1tyiyv3jQjCCfoQEeJkp0J0Kpl8/5Bm9BMg0lq8DdCKm+/UCZC/NTp242fBswAw5DYXo5UlT/MnEYTnDmMdcZcexKnHj2caZiYQ12I6urknNoYdIkJPM/RYJT7JLr3W8qRWNbwJfwpDJwArpa+H0MNMIKwJcAcWmFle3Z+G2NaOJcEhpmC2V5mSLK53oXmhZhebq754B/s="
    file_glob: true # http://stackoverflow.com/a/28579635/1320237
    file: "/home/travis/${image_name}"
    on:
      all_branches: true
